
version: "3.5"

services:
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=marko
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4:latest
    restart: on-failure
    ports:
      - 5050:80
    links:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=markoperajicca@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin_data:
