version: "3.5"

x-logging:
 &logging-config
 logging:
  driver: json-file
  options:
   max-size: "200k"
   max-file: "10"
x-healthcheck:
 &healthcheck-config
 healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3


services:

  nginx-root:
    image: nginx-root:latest
    <<: *logging-config
    <<: *healthcheck-config

  client:
    image: sba_client:latest
    restart: on-failure
    <<: *logging-config
    <<: *healthcheck-config
    ports:
     - 3000:3000

  db:
   image: postgres:latest
   <<: *logging-config
   <<: *healthcheck-config
   restart: on-failure
   ports:
    - 5000:5432
   environment:
    - POSTGRES_USER=marko
    - POSTGRES_PASSWORD=admin123
   volumes:
    - postgres_data:/var/lib/postgresql/data

  pg-admin:
   image: dpage/pgadmin4:latest
   <<: *logging-config
   <<: *healthcheck-config
   restart: on-failure
   ports:
    - 5050:80
   links:
    - db
   environment:
    - PGADMIN_DEFAULT_EMAIL=markoperajicca@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=admin123
    - PGADMIN_LISTEN_PORT=80
   volumes:
    - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin_data:
