import React from "react";
import { Grid, Image, Header, Container, Divider } from "semantic-ui-react";

const EthereumStack = props => {
  return (
    <div>
      <Grid padded="vertically" container>
        <Grid.Row columns={2}>
          <Grid.Column>
            <Image
              as="img"
              src="https://www.goodfreephotos.com/cache/other-photos/bitcoin-ethereum-and-world-coin.jpg"
              size="large"
              centered
              style={{ paddingTop: "10px", borderRadius: "25px" }}
            />
          </Grid.Column>
          <Grid.Column
            as="div"
            style={{ textAlign: "center", fontFamily: "Roboto Slab, serif" }}
          >
            <Container
              as="div"
              style={{ fontWeight: "bold", paddingTop: "30px" }}
            >
              Ethereum Technology
            </Container>
            <Divider />
            <Container as="div" style={{ fontFamily: "'Lato', sans-serif" }}>
              Ethereum is a global, open-source platform for decentralized
              applications.
              <Divider hidden />
              Ether is a cryptocurrency whose blockchain is generated by the
              Ethereum platform. Ether can be transferred between accounts and
              used to compensate participating mining hubs for calculations
              performed. Ethereum provides a decentralized Turing-complete
              virtual machine , the Ethereum Virtual Machine (EVM), which can
              execute scripts using an international network of public hubs.
              “Gas,” an internal transactional valuation device, is used to
              mitigate spam and allocate resources to the network.
            </Container>
          </Grid.Column>
        </Grid.Row>
      </Grid>
    </div>
  );
};

export default EthereumStack;
