version: '3.5'


x-logging:
 &logging-config
 logging:
  driver: json-file
  options:
   max-size: "200k"
   max-file: "10"
x-healthcheck:
 &healthcheck-config
 healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3


services:

# client:
  #image: sba_client:latest
#  restart: on-failure
   #<<: *logging-config
   #<<: *healthcheck-config
#  ports:
#   - 3000:3000
 node-1:
  image: hyperledger/besu:latest
  hostname: node-1
  restart: on-failure
  ports:
   - 8545:8545
   - 8546:8546
   - 8547:8547
   - 30303:30303/tcp
   - 30303:30303/udp
  volumes:
   - ./bootnode_config.toml:/config/config.toml
   - ./genesis.json:/config/genesis.json
   - ./networkFiles/keys/node-1:/opt/besu/keys
   - volume_besu_node_1:/opt/besu
  networks:
   besu-net:
    ipv4_address: 172.16.239.1
  entrypoint:
   - /bin/sh
   - -c
   - |
    /opt/besu/bin/besu public-key export --to=/tmp/bootnode_pubkey;
    /opt/besu/bin/besu \
    --config-file=/config/config.toml \
    --genesis-file=/config/genesis.json \
    --node-private-key-file=/opt/besu/keys/key \
    --rpc-http-port=8545 \
    --rpc-ws-port=8546 \
    --p2p-port=30303 \
    --rpc-http-api=ETH,MINER,IBFT,NET,WEB3 \
    --bootnodes;

 node-2:
  image: hyperledger/besu:latest
  hostname: node-2
  restart: on-failure
  ports:
   - 30304:30304/tcp
   - 30304:30304/udp
  depends_on:
   - node-1
  volumes:
   - ./node_config.toml:/config/config.toml
   - ./genesis.json:/config/genesis.json
   - ./networkFiles/keys/node-2:/opt/besu/keys
   - volume_besu_node_2:/opt/besu
  networks:
   besu-net:
    ipv4_address: 172.16.239.2
  links:
   - node-1
  entrypoint:
   - /bin/sh
   - -c
   - |
    sleep 10;
    /opt/besu/bin/besu \
    --genesis-file=/config/genesis.json \
    --config-file=/config/config.toml \
    --node-private-key-file=/opt/besu/keys/key \
    --p2p-port=30304 \
    --rpc-http-port=8548 \
    --rpc-ws-port=8549 \
    --rpc-http-api=ETH,MINER,IBFT,NET;


 node-3:
  image: hyperledger/besu:latest
  hostname: node-3
  restart: on-failure
  ports:
   - 30305:30305/tcp
   - 30305:30305/udp
  depends_on:
   - node-1
  volumes:
   - ./node_config.toml:/config/config.toml
   - ./genesis.json:/config/genesis.json
   - ./networkFiles/keys/node-3:/opt/besu/keys
   - volume_besu_node_3:/opt/besu
  networks:
   besu-net:
    ipv4_address: 172.16.239.3
  links:
   - node-1
  entrypoint:
   - /bin/sh
   - -c
   - |
    sleep 10;
    /opt/besu/bin/besu \
    --genesis-file=/config/genesis.json \
    --config-file=/config/config.toml \
    --node-private-key-file=/opt/besu/keys/key \
    --rpc-http-port=8551 \
    --rpc-ws-port=8552 \
    --p2p-port=30305 \
    --rpc-http-api=ETH,MINER,IBFT,NET;

 node-4:
  image: hyperledger/besu:latest
  hostname: node-4
  restart: on-failure
  ports:
   - 30306:30306/tcp
   - 30306:30306/udp
  depends_on:
   - node-1
  volumes:
   - ./node_config.toml:/config/config.toml
   - ./genesis.json:/config/genesis.json
   - ./networkFiles/keys/node-4:/opt/besu/keys
   - volume_besu_node_4:/opt/besu
  networks:
   besu-net:
    ipv4_address: 172.16.239.4
  links:
   - node-1
  entrypoint:
   - /bin/sh
   - -c
   - |
    sleep 10;
    /opt/besu/bin/besu \
    --genesis-file=/config/genesis.json \
    --config-file=/config/config.toml \
    --node-private-key-file=/opt/besu/keys/key \
    --rpc-http-port=8554 \
    --rpc-ws-port=8555 \
    --p2p-port=30306 \
    --rpc-http-api=ETH,MINER,IBFT,NET;

volumes:
 volume_besu_node_1:
 volume_besu_node_2:
 volume_besu_node_3:
 volume_besu_node_4:

networks:
  besu-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
